### ISSUE TITLE
User flyout blocks scrolling

### ISSUE THREAD

**Issue by josephg** [sandstorm-io/sandstorm#1921]
The CSS on the top-right user flyout (either for login/logout or anything else) makes the element fullscreen and blocks scrolling on the rest of the page:

![image](https://cloud.githubusercontent.com/assets/47413/14908476/edd4a366-0e1a-11e6-81ab-2ff641ab473f.png)

CSS:

```css
body>.popup {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 100000;
}
```

Removing the `bottom` and `left` tags fixes it:

```css
body>.popup {
  position: fixed;
  top: 0;
  right: 0;
  z-index: 100000;
}
```
