### ISSUE TITLE
docker compose unshare(CLONE_NEWPID)

### ISSUE THREAD

**Issue by antonio24073** [sandstorm-io/sandstorm#3695]
Hi,
I'm trying to create a docker compose file with a swarm service  in fedora 37.
```
version: '3.7'
services:
  sandstorm:
    user: root
    tty: true
    ports:
      - target: 6080
        published: 6080
        mode: host
    image: buildpack-deps:stable
    deploy:
      restart_policy:
        condition: none
    command: bash -c "useradd --system --user-group sandstorm; curl https://install.sandstorm.io/ > install.sh; bash install.sh -d -e; /opt/sandstorm/sandstorm start && sleep infinity" 
    # volumes:
    #     - '/home/antonio/projects/docker/sandstorm:/opt/sandstorm'
```
And when I do `docker stack deploy -c docker-compose.yml sandstorm` I'm getting:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78583  100 78583    0     0  16070      0  0:00:04  0:00:04 --:--:-- 18304
Sandstorm makes it easy to run web apps on your own server. 
Config written to /opt/sandstorm/sandstorm.conf.
Finding latest build for dev channel...
Downloading: https://dl.sandstorm.io/sandstorm-307.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 73.9M  100 73.9M    0     0  10.5M      0  0:00:07  0:00:07 --:--:-- 10.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0   4025      0 --:--:-- --:--:-- --:--:--  4025
GPG signature is valid.
*** Uncaught exception ***
sandstorm/run-bundle.c++:543: failed: unshare(CLONE_NEWPID): Operation not permitted
stack: 6206ba 6202cc 494406 494849
*** Uncaught exception ***
sandstorm/run-bundle.c++:543: failed: unshare(CLONE_NEWPID): Operation not permitted
stack: 6206ba 6202cc 494406 494849
```
Thank you friend.
